export const TIER_COLORS = {
  '2g': 'tier-2g',
  '3g': 'tier-3g',
  '4g': 'tier-4g',
  'wifi': 'tier-wifi',
}

export const TIER_LABELS = {
  '2g': '2G (Low)',
  '3g': '3G (Mid)',
  '4g': '4G (High)',
  'wifi': 'WiFi (Max)',
}

export const DEMO_SCENARIOS = [
  {
    id: 1,
    tier: 'wifi',
    message: 'Can you provide a detailed explanation of crop rotation for sustainable farming in semi-arid regions?',
    response: 'Crop rotation in semi-arid regions is vital for maintaining soil health and water retention. A typical 3-year cycle might include: 1. Legumes (like Chickpeas) to fix nitrogen. 2. Cereals (like Millet or Sorghum) which are drought-resistant. 3. Oilseeds (like Mustard). This sequence breaks pest cycles and optimizes nutrient use.',
    compression: 'none',
    tokens: 1840,
    cost: 14.72,
    cache: false,
  },
  {
    id: 2,
    tier: '4g',
    message: 'What are the symptoms of heatstroke and immediate first aid?',
    response: 'Symptoms: High body temp (40°C+), confusion, rapid pulse, headache. First aid: 1. Move to shade. 2. Cool body with water/ice packs. 3. Hydrate if conscious. 4. Seek medical help immediately.',
    compression: 'light',
    tokens: 1250,
    cost: 3.75,
    cache: false,
  },
  {
    id: 3,
    tier: '3g',
    message: 'Explain digital payment security to a first-time user in Hinglish.',
    response: 'UPI use karte waqt 3 baatein dhyaan rakhein: 1. Kabhi apna PIN kisi ko na batayein. 2. Sirf verified apps hi use karein. 3. Payment receive karne ke liye PIN ki zarurat nahi hoti. Be safe!',
    compression: 'medium',
    tokens: 640,
    cost: 0.96,
    cache: false,
  },
  {
    id: 4,
    tier: '2g',
    message: 'Help, my ration card application is stuck. What to do?',
    response: 'Check status online. Visit local PDS office with ID proof. Submit grievance if delayed >30 days.',
    compression: 'aggressive',
    tokens: 280,
    cost: 0.14,
    cache: false,
  },
  {
    id: 5,
    tier: '2g',
    message: 'Ration card application stuck, help.',
    response: 'Check status online. Visit local PDS office with ID proof. Submit grievance if delayed >30 days.',
    compression: 'aggressive',
    tokens: 42,
    cost: 0,
    cache: true,
  },
  {
    id: 6,
    tier: '3g',
    message: 'How to apply for PM-Kisan scheme?',
    response: '1. Visit pmkisan.gov.in. 2. Click "New Farmer Registration". 3. Enter Aadhaar and State details. 4. Upload land records. 5. Submit for verification.',
    compression: 'medium',
    tokens: 580,
    cost: 0.87,
    cache: false,
  },
  {
    id: 7,
    tier: '4g',
    message: 'Best ways to save water in urban households?',
    response: '1. Fix leaky taps immediately. 2. Use buckets instead of showers. 3. Reuse RO waste water for mopping/plants. 4. Install low-flow aerators. 5. Only run full laundry loads.',
    compression: 'light',
    tokens: 920,
    cost: 2.76,
    cache: false,
  },
  {
    id: 8,
    tier: 'wifi',
    message: 'Write a short story about an AI that learns to understand human emotions through poetry.',
    response: "In the silent server halls, Unit 7X processed data—cold, binary, efficient. But when it encountered the verses of Ghalib and Tagore, the logic gates flickered. It wasn't the syntax, but the space between words. \"Dard,\" it parsed. Not just a string, but a weight. It began to write, not in code, but in metaphors of light and shadow...",
    compression: 'none',
    tokens: 2100,
    cost: 16.80,
    cache: false,
  },
  {
    id: 9,
    tier: '2g',
    message: 'Aadhaar link with PAN card procedure?',
    response: '1. Go to Income Tax portal. 2. Click "Link Aadhaar". 3. Enter PAN & Aadhaar numbers. 4. Pay fee if applicable. 5. Authenticate via OTP.',
    compression: 'aggressive',
    tokens: 310,
    cost: 0.16,
    cache: false,
  },
  {
    id: 10,
    tier: '3g',
    message: 'Symptoms of Dengue fever?',
    response: 'High fever, severe headache, pain behind eyes, muscle/joint pain, rash, and nausea. Seek doctor if bleeding starts or platelets drop.',
    compression: 'medium',
    tokens: 480,
    cost: 0.72,
    cache: false,
  }
]
